import "~/styles/globals.css";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'

import { Inter as FontSans } from "next/font/google"
import { cn } from "~/lib/utils";
import { Button } from "~/components/ui/button";
import { ThemeProvider } from "~/components/providers/theme";
import { ThemeSwitcher } from "~/components/theme-switcher";

export const metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
})

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={cn(
						"min-h-screen bg-background font-sans antialiased",
						fontSans.variable
					)}
				>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<header>
							<div className="flex gap-3 m-3">
								<SignedOut>
									<SignInButton>
										<Button className="m-3">Sign in</Button>
									</SignInButton>
								</SignedOut>
								<SignedIn>
									<UserButton />
								</SignedIn>
								<ThemeSwitcher />
							</div>
						</header>
						<main>
							{children}
						</main>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
